// <auto-generated />
using ACupOfCoffee.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ACupOfCoffee.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180425194814_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ACupOfCoffee.Models.Entities.Cup", b =>
                {
                    b.Property<int>("CupId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<int>("Duration");

                    b.Property<DateTime>("EndTime");

                    b.HasKey("CupId");

                    b.ToTable("Cups");
                });
#pragma warning restore 612, 618
        }
    }
}
